name: Docker Image CI

on:
  push:
    tags: [ v* ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Get github reference variables
      id: var
      run: echo ::set-output name=tags::${GITHUB_REF#refs/*/}

    - name: Build turtlemq and export to Docker
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USER}}/turtlemq:${{ steps.var.outputs.tags }} , ${{secrets.DOCKER_USER}}/turtlemq:latest
        
    - name: Build turtlewatcher and export to Docker
      uses: docker/build-push-action@v3
      with:
        context: ./turtleWatcher
        file: ./turtleWatcher/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USER}}/turtlewatcher:${{ steps.var.outputs.tags }} , ${{secrets.DOCKER_USER}}/turtlewatcher:latest
